### ISSUE TITLE
killed

### ISSUE THREAD

**Issue by FrankXinqi** [CasparSwift/CLIM#3]
When training for the first epoch, it is killed by the system
![Screen Shot 2022-02-21 at 1 28 41 AM](https://user-images.githubusercontent.com/13465175/154855723-ed34770b-c9fa-4726-8878-a0c8c5c0ae13.png)

**Comment by CasparSwift** [comment]
memory exceeds? you may decrease default num_workers=32 or batch_size

**Comment by FrankXinqi** [comment]
Yes. I think `num_workers` is the problem. I have only 10 cpu cores on my local machine. It works by changing this `num_workers to 4`.

BTW, was the best performance obtain from 8 GPUs? How many GPUs and what GPUs did you use? I only have 2 2080Ti. I make it work with `batch_size=6`, where you have `24` originally.

**Comment by CasparSwift** [comment]
We obtain our results with batch_size=24 on 6 Tesla M40 or K80 GPUs. Each has ~12 GB memory. 
Larger batch size indicates more negative samples for contrastive learning, so it may slightly improve the performance.

**Comment by FrankXinqi** [comment]
Thank you so much for your response.
