### ISSUE TITLE
How did you augment the data?

### ISSUE THREAD

**Issue by FrankXinqi** [CasparSwift/CLIM#4]
It seems the online data augmentation is not used? https://github.com/CasparSwift/CLIM/blob/7f8fe9628b338c4da957c8e6edb7c77e562480f8/dataset.py#L130 

Do you preform back translation off-line and save it? Could you please give some details about it?

**Comment by CasparSwift** [comment]
Yes.
Online data augmentation is time-consuming, so we preprocess the data with back translation augmentation

**Comment by CasparSwift** [comment]
Yes. One original and one augmented data.
