### ISSUE TITLE
Update on requirements.txt

### ISSUE THREAD

**Issue by vsablok123** [CasparSwift/CLIM#7]
Hi,
Do you have an update on the requirments.txt file for this repo. The reason is that the env created using the current file is giving errors.
  
  lementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
    warnings.warn(
  Traceback (most recent call last):
    File "train.py", line 171, in <module>
      optimizers = optimizer_factory[args.model_name](args, model, total_steps=len(
    File "/home/grp-gpu-nc/Polarity_Detection/CLIM/optimizers.py", line 17, in __init__
      self.optimizer = AdamW(optimizer_grouped_parameters, lr=args.learning_rate, eps=1e-8)
    File "/home/grp-gpu-nc/anaconda3/envs/clim_env/lib/python3.8/site-packages/transformers/optimization.py", line 312, in __init__
      require_version("torch>=1.5.0")  # add_ with alpha
    File "/home/grp-gpu-nc/anaconda3/envs/clim_env/lib/python3.8/site-packages/transformers/utils/versions.py", line 116, in require_version
      _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
    File "/home/grp-gpu-nc/anaconda3/envs/clim_env/lib/python3.8/site-packages/transformers/utils/versions.py", line 49, in _compare_versions
      raise ImportError(
  ImportError: torch>=1.5.0 is required for a normal functioning of this module, but found torch==1.4.0.

**Comment by vsablok123** [comment]
No worries. I was able to make the code work with torch==1.5.0. The incompatibility could be due to using the latest transformers version 4.22.1.

I had another question: In the paper, the team talks about in-domain and overall contrastive loss for training. While in the train.py, we do not see an argument/parameter to control this setting. 
Has it been hardwired in this github repo to only in-domain contrastive loss?? (Looking at this piece of code from loss.py lines 424-431)

```       
        if z2_src is not None and z1_src is not None:
            contrast_loss1 = self.InfoNCE_loss(z1_src, z2_src)
        else:
            contrast_loss1 = torch.tensor(0.)
        if z2_tgt is not None and z1_tgt is not None:
            contrast_loss2 = self.InfoNCE_loss(z1_tgt, z2_tgt)
        else:
            contrast_loss2 = torch.tensor(0.)
```

**Comment by CasparSwift** [comment]
Yes, we implement in-domain contrastive loss in loss.py (what we called "domain_aware_xxx" in our code). You may modify the "loss_factory" variable in loss.py to control this setting.

**Comment by vsablok123** [comment]
Got it, Thank you.
